name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: $GITHUB_ACTOR
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${GITHUB_REPOSITORY}/tyler:latest
      env:
        GITHUB_REPOSITORY: $GITHUB_REPOSITORY
    - name: Push to Github
      run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/tyler:latest
      env:
        GITHUB_REPOSITORY: $GITHUB_REPOSITORY
